version: "2"
services:
  redis:
   image: redis:latest
   
  hubot:
   image: boxytv.azurecr.io/hubot:latest
   environment:
    - HUBOT_SLACK_TOKEN=${HUBOT_SLACK_TOKEN}
    - HUBOT_NAME=${HUBOT_NAME}
    - HUBOT_URL=${HUBOT_URL}
    - HUBOT_PAPERSPACE_API_KEY=${HUBOT_PAPERSPACE_API_KEY}
   links:
    - redis:redis
   ports:
    - "8081:8080"
